### ISSUE TITLE
Modify the Makefile

### ISSUE THREAD

**Issue by bijaychamlagain** [inft3063-assignment-1-wed-atb/INFT2063_Assignment_1-v02#11]
Modify the Makefile to include the creation of a jar file

**Comment by bijaychamlagain** [comment]
As a JAR is a package file format typically used to aggregate many Java class files and associated metadata and resources (text, images, etc.) into one file for distribution, I think our Makefile should also include some jar file creation  code like **_jar cf jar-file input-file(s)_** I dont know if this works but we can try. To make it an executable jar file we might need a manifest file too.

**Comment by bijaychamlagain** [comment]
I have made some changes to the Makefile. Can someone confirm the makefile is creating an executable jar file and the jar program is running without any errors?

**Comment by Anthony-T-N** [comment]
Can confirm and verify your patch/fix is allowing the MakeFile to create an executable jar file. Can run jar without any errors and runs smoothly.
Closing issue as this as been resolved.
