### ISSUE TITLE
Add Welcome Message

### ISSUE THREAD

**Issue by tin-nguyen12** [inft3063-assignment-1-wed-atb/INFT2063_Assignment_1-v02#12]
Add a nice welcoming message to the user when the program starts

**Comment by bijaychamlagain** [comment]
User is greeted with a welcome text when they start the program for the first time.

**Comment by bijaychamlagain** [comment]
The previous ASCII welcome message was not supported when the program was executed through a windows computer. The welcome message will be updated to support all platform.
