### ISSUE TITLE
Add Error Handling

### ISSUE THREAD

**Issue by tin-nguyen12** [inft3063-assignment-1-wed-atb/INFT2063_Assignment_1-v02#13]
Add eloquent error handling in case of unexpected input from the user. Ensure the error is easy to understand what the user did incorrectly.

**Comment by Anthony-T-N** [comment]
Additional error handling checks were added to prevent the user from proceeding with the transaction with invalid inputs.
Error handling was applied to prompts that asked for the cash register float, item cost, and cash tendered.
Note: Variable nextItem was set to true to allow the user to proceed with the transaction once again.
