### ISSUE TITLE
Add User Authentication to the program

### ISSUE THREAD

**Issue by tin-nguyen12** [inft3063-assignment-1-wed-atb/INFT2063_Assignment_1-v02#16]
Add a feature that allows the user to be able to login into the system. Correct username and password grants them access and repeated incorrect login attempts should temporarily lock them out. It should also include the ability to be able to create new logins.

**Comment by Anthony-T-N** [comment]
Successfully added the new feature that allows users to create new usernames and passwords to log into the system. Invalid attempts are counted and too many of them will lock the user out for the current session.
