### ISSUE TITLE
Create a Daily Summary Report

### ISSUE THREAD

**Issue by tin-nguyen12** [inft3063-assignment-1-wed-atb/INFT2063_Assignment_1-v02#18]
Add a feature where the program will automatically create a summary report of the transactions that was made. The report will be generated once the program is terminated.

**Comment by bijaychamlagain** [comment]
A summary report for sales and inventory management was created. A summary is displayed and a text output of the report is also generated every time before the system exits. The report has information about inventory and all the transactions generated during the system uptime.
