### ISSUE TITLE
Implement a Guest Login for User Authentication 

### ISSUE THREAD

**Issue by tin-nguyen12** [inft3063-assignment-1-wed-atb/INFT2063_Assignment_1-v02#24]
Optimise feature to allow the user to be able to login without an existing account. Used for testing purposes and allow the usage of the register for who want a demo.

**Comment by skaranzx16** [comment]
Hey, could I take this issue up and work on it?

**Comment by Anthony-T-N** [comment]
Hey Sreekaran, unfortunately yes, this is a course assignment so we can't accept outside help at the moment. But we do appreciate your offer to help us.
