### ISSUE TITLE
Resolve error when exporting reports in Windows

### ISSUE THREAD

**Issue by Anthony-T-N** [inft3063-assignment-1-wed-atb/INFT2063_Assignment_1-v02#28]
Resolve error where program has difficulty exporting reports in the form of a text file on Windows.

**Comment by bijaychamlagain** [comment]
Hi, @Anthony-T-N  @tinothy 
I have made a few changes in the report file which might have fixed the error. I think the error was with the name of the text file generated by the system which had space in between, can you check and confirm if it is working.

**Comment by Anthony-T-N** [comment]
Can confirm that the report is being generated successfully and the contents of the report file is left unhindered. You are free to close this issue.
