### ISSUE TITLE
Incorrect change values

### ISSUE THREAD

**Issue by tin-nguyen12** [inft3063-assignment-1-wed-atb/INFT2063_Assignment_1-v02#3]
The program outputs the incorrect change values. Correct it so that is displays the right amount

**Comment by Anthony-T-N** [comment]
Identified error in the "CashRegister.java" file where the cost of an item was incorrectly being added instead of subtracted from input. 
The identified second error in "Transaction.java" file where the "getCost()" method unnecessarily multiplied value by 2.
