### ISSUE TITLE
Implement User Input Validation

### ISSUE THREAD

**Issue by tin-nguyen12** [inft3063-assignment-1-wed-atb/INFT2063_Assignment_1-v02#30]
Prevent users from being able to input negative numbers such as in when asking for item price and quantity of items. Positive numbers is the only allowed form

**Comment by bijaychamlagain** [comment]
That is a very good thing to validate, I think we should also validate all the user input like the number of text allowed in the item name, number of digit in the amount and so on. Will work on it as soon as possible.

**Comment by bijaychamlagain** [comment]
Userinput for amount can not be less than 0 and more than one million.
Quantity can not be more than 1000 and less than 0. Item name must be
less than 100 characters.
